<?php

namespace BasketBundle\Repository;

/**
 * BasketEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketEntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getColiAdvanced($name="",$qte=""){
        $query = $this->createQueryBuilder('c')
            ->Where('c.nom LIKE :nom')
            ->setParameter('nom', '%'.$name.'%')
            ->AndWhere('c.quantite LIKE :qte')
            ->setParameter('qte', '%'.$qte.'%')
            ->getQuery();
        return $query->execute();
    }
}
